spring.application.name=interview-lab

spring.datasource.mysql.jdbc-url=jdbc:mysql://localhost:3306/interview_lab
spring.datasource.mysql.username=root
spring.datasource.mysql.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ye bad me dekhena h
spring.jpa.open-in-view=false

# h2 datasource config
app.datasource.h2.jdbc-url=jdbc:h2:mem:interview_audit;DB_CLOSE_DELAY=-1
app.datasource.h2.username=sa
app.datasource.h2.password=
app.datasource.h2.driver-class-name=org.h2.Driver

# enable h2 console
spring.h2.console.enabled=true

# ehcache
spring.cache.type=jcache
spring.cache.jcache.config=classpath:ehcache.xml